Fixes #151 DomainOfExpertise from session
RHEAGROUP/CDP4-SDK-Community-Edition pull request #152
Opened 2020-11-20 16:19 UTC by lxatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/pulls) open
- [x] I have verified that I am following the CDP4-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-SDK-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
Bugfix and refactoring DomainOfExpertise from Session/ISession

2020-11-21 10:58 UTC, alexatrhea requested changes

2020-11-21 10:58 UTC, alexatrhea commented on CDP4Dal/CDP4Dal.csproj
> +    <VersionPrefix>6.3.1</VersionPrefix>
This is a non-backwards compatible change. I think this will be SDK 7.0.0.

2020-11-22 08:34 UTC, samatrhea requested changes

2020-11-22 08:34 UTC, samatrhea commented on CDP4Dal/ISession.cs
>          /// Queries the <see cref="Participant"/>'s <see cref="DomainOfExpertise"/>'s from the session for the current <see cref="Iteration"/>
please update the docs -> current iteration needs to become `provided iteration` and the `returns` statement needs to be updated as well

2020-11-22 08:34 UTC, samatrhea commented on CDP4Dal/Session.cs
> -        public DomainOfExpertise QueryCurrentDomainOfExpertise()
i think there was indeed already a method called `QuerySelectedDomainOfExpertise(Iteration iteration)` that was taking care of this, and indeed, it needs an `Iteration` as parameter

2020-11-22 08:34 UTC, samatrhea commented on CDP4Dal/ISession.cs
> +        IEnumerable<DomainOfExpertise> QueryDomainOfExpertise(Iteration iteration);
in the source file, can this method be placed after the existing `QuerySelectedDomainOfExpertise`, then they are close to eachother, should be easier to maintain the code in the future.

2020-11-23 08:48 UTC, samatrhea requested changes
the docs on returns seem to be incorrect

2020-11-23 08:48 UTC, samatrhea commented on CDP4Dal/ISession.cs
> +        /// The <see cref="DomainOfExpertise"/> if selected, null otherwise.
this is incorrect

2020-11-23 08:48 UTC, samatrhea commented on CDP4Dal/Session.cs
> +        /// The <see cref="DomainOfExpertise"/> if selected, null otherwise.
this is incorrect

2020-11-23 09:21 UTC, samatrhea approved these changes

2020-11-23 09:43 UTC, alexatrhea approved these changes

2020-11-23 10:58 UTC, merged