Fixes #158 Added ISession.BeforeWrite event
RHEAGROUP/CDP4-SDK-Community-Edition pull request #159
Opened 2020-12-11 11:26 UTC by lxatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/pulls) open
- [x] I have verified that I am following the CDP4-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-SDK-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
Added ISession.BeforeWrite event

2020-12-11 12:26 UTC, ahmedatrhea approved these changes

2020-12-14 09:38 UTC, samatrhea requested changes

2020-12-14 09:38 UTC, samatrhea commented on CDP4Dal/Session.cs
> +        public OperationContainer OperationContainer { get; }
please add more xml docs

2020-12-14 09:38 UTC, samatrhea commented on CDP4Dal/Session.cs
> +    public class BeforeWriteEventArgs : EventArgs
my preference is to have a file per class

2020-12-14 11:08 UTC, samatrhea approved these changes
just some new lines in some files

2020-12-14 11:08 UTC, samatrhea commented on CDP4Dal.Tests/Events/BeforeWriteEventArgsTestFixture.cs
> +}
new line?

2020-12-14 11:08 UTC, samatrhea commented on CDP4Dal.NetCore.Tests/Events/BeforeWriteEventArgsTestFixture.cs
> +}
new line

2020-12-14 11:14 UTC, nathanatrhea approved these changes

2020-12-14 20:25 UTC, alexatrhea approved these changes

2020-12-15 08:15 UTC, merged