[REFACTOR] Remove DotNetZip, replace with SharpZipLib; fixes #349
RHEAGROUP/CDP4-SDK-Community-Edition pull request #353
Opened 2024-10-21 12:13 UTC by lxatstariongroup

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/STARIONGROUP/COMET-SDK-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-SDK [code style guidelines](https://raw.githubusercontent.com/STARIONGROUP/COMET-SDK-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
[REFACTOR] Remove DotNetZip, replace with SharpZipLib; fixes #349

2024-10-21 12:38 UTC, samatstariongroup approved these changes

2024-10-23 08:45 UTC, samatstariongroup requested changes
please refactor the utils calss to make the methods extensions methods

please declare the bitness (256) as a static field (or the like) so this is explicit and we don;t have 256 in different places in the code

2024-10-23 08:45 UTC, samatstariongroup commented on CDP4Common/Encryption/SharpZipLibUtils.cs
> +        public static void AddEntryFromStream(ZipOutputStream zipOutputStream, Stream stream, string name)
please make this an extension method

2024-10-23 09:01 UTC, lxatstariongroup commented on CDP4Common/Encryption/SharpZipLibUtils.cs
> +        public static void AddEntryFromStream(ZipOutputStream zipOutputStream, Stream stream, string name)
done

2024-10-23 13:10 UTC, merged